- .Rbuildignore
Fix R CMD note:
```
❯ checking top-level files ... NOTE
Non-standard file/directory found at top level:
‘README.Rmd’
```
> Avoid note about non-standard file in root

- DESCRIPTION
ggsignif is a dependency of ggpubr. Usually we do not need to install a dependency of a dependency but here I do it as a hack.
I don't know why, but GitHub actions is failing to install ggsignif from CRAN. To get around this problem, this PR installs ggsignif from GitHub instead of CRAN. This won't be acceptable when you submit to CRAN, but by then I hope to have pruned as many dependencies as possible, maybe including ggpubr -- which seems quite heavy.
> Suggest problematic 'ggsignif' package from GitHub

- tests/testthat/_snaps/get_example_data.md
- tests/testthat/test-get_example_data.R
This PR fixes a problem I saw on CI. A snapshot was failing because the print method of tibble was slightly different locally versus CI. Tibble likely includes a way to deal with this more elegantly, but instead here I use the simpler approach of converting the tibble to a vanilla dataframe -- which prints the same everywhere.
(As of this writing I see some checks failing on macos and windows but for a reason that is irrelevant to this PR. That problem is fixed at #57.)
> Store a more robust snapshot

- R/imports.R
- R/plot_timeline.R
- R/prepare_for_timeline.R
- man/plot_timeline.Rd
- tests/testthat/test-prepare_for_timeline.R
This PR is to be merged not into `master` but into https://github.com/2DegreesInvesting/r2dii.ggplot/pull/59. It adds a bit of code to handle factors smoothly, and exposes a bug when `extrapolate_missing_values = TRUE` and R 3.6.3 (maybe any R < 4).
Here is a cloud project that exposes this issue: https://rstudio.cloud/project/2405399
> Handle factors and flag FIXME

- R/2dii_colours.R
Closes #89
Exclude code which results in an artifact of low coverage.
The file R/2dii_colours.R is fully covered by tests:
I expected `covr::package_coverage()` to report 100% cover but instead it reports 79.25%. This is weird and maybe a bug in covr or devtools but we can go around it by [excluding the relevant chunk of code from the code coverage analysis.](https://github.com/r-lib/covr#exclusion-comments)
> Use exclusion comments

- DESCRIPTION
- R/plot_timeline.R
- tests/testthat/_snaps/plot_timeline.md
On master, the order of the legend does not match the order of the
plot lines: 
Now they do
This is the recommended approach to plotting lines and legends:
https://twitter.com/JennyBryan/status/1244499728831672320?s=20
With this change, I we may not need to ask the user to provide
the order, making the interfaces simpler.
While I'm here, I refactored to simplify the body of `plot_timeline()`. The
snapshot changed but as far as I can tell the result is as expected.
Example:
``` r
devtools::load_all()
#> ℹ Loading r2dii.plot.static
specs <- tibble::tribble(
~line_name,           ~label, ~colour_hex,
"projected",          "Proj.",   "#1b324f",
"corporate_economy",  "Corp. Economy",   "#00c082",
"target_demo",         "Target",   "#ff9623",
"adjusted_scenario_demo",  "Adj. Scenario", …
```
> In plot_timeline(), order legend to match lines

- .github/workflows/render-rmarkdown.yaml
Closes #170
﻿This should expose problems in .Rmd files, which may be out of sync with the production code. AFAIK, this workflow is fairly new and I'm not sure how robust it is but I think it's worth trying.
usethis::use_github_action("render-rmarkdown.yaml")
<https://github.com/r-lib/actions/tree/master/examples>
> Add workflow to render all rmarkdown documents

- R/plot_trajectoryY.R
- vignettes/articles/r2dii-plot-X-versus-Y.Rmd
- vignettes/articles/r2dii-plot-X.Rmd
- vignettes/articles/r2dii-plot-Y.Rmd
In this PR I add further examples to articles in order to align the two versions.
There is also one change made in the `plot_trajectoryY()` code to align the two versions (the label is derived from data if not specified).
> Align X and Y articles for techmix and trajectory

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/test-coverage.yaml
This PR update relevant gh-actions workflows so they are
triggered by actions on the new branch 'develop'.
﻿
> GH workflows now work with branch 'develop'

- _pkgdown.yml
This PR fixes the website's reference to remove duplicated references to the datasets. Not sure why.
It is a fix and touches no production code so I'll merge with no further review.
> Fix website reference

- R/plot_emission_intensity.R
- R/plot_trajectory.R
- R/utils.R
- man/plot_emission_intensity.Rd
This relates to a previous issue. Somehow some "timeline"
strings survived. This PR changes them to "emission
intensity".
This is well agreed and internal so I'll merge with no
further review.
> Rename to emission intensity

- tests/testthat/test-plot_techmix.R
- tests/testthat/test-plot_trajectory.R
?subset:
> Warning
> This is a convenience function intended for use interactively.
> For programming it is better to use the standard subsetting
> functions like [, and in particular the non-standard evaluation
> of argument subset can have unanticipated consequences.
dplyr::filter() also uses non-standard evaluation but is safe to
program with thanks to the tidy eval framework.
> In internal code use dplyr::filter() not subset()

- tests/testthat/test-plot_techmix.R
- tests/testthat/test-sda.R
- New integration test for sda
We had one for market_share but not sda. The idea is to
automatically check that the helpifle of sda keeps its
promise, i.e. that sda has the structure as the output
of r2dii.analysis::target_sda().
> New integration test for sda

- R/market_share.R
- R/plot_emission_intensity.R
- R/sda.R
- R/theme_2dii.R
- man/market_share.Rd
- man/sda.Rd
- man/theme_2dii.Rd
Also avoid this:
#> Warning: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
> Polish documentation

- R/plot_trajectory.R
Closes #261 
In this PR I simplify the code of `get_area_borders()` so that one of the `if` statements is dropped and the test coverage increases.
> Simplify get_area_borders code

- R/r2dii_colours.R
In the first release we removed internal documentation to minimize
the chances that CRAN would find some problem with it. This PR
restores that internal documentation that should be hidden from the
public website but available at */reference/r2dii.colours.html﻿
> Do generate internal helpfile for r2dii_colours

- R/plot_trajectory.R
- R/qplot_trajectory.R
- tests/testthat/_snaps/qplot_trajectory.md
Closes #347 
In this PR I make the space left for annotations data-dependent instead of hardcoded 6 years. 
Minor change: wrap the trajectory title.
> Modify annotation space

- R/theme_2dii.R
In this PR I pass the `base_size` argument passed by the user to `theme_classic()` so that all the sizes in the plot are adjusted correctly.
Makes the #384 redundant.
> Adjust the base_size according to specs

- R/plot_emission_intensity.R
- R/plot_techmix.R
- R/plot_trajectory.R
- R/qplot_emission_intensity.R
- R/qplot_techmix.R
- R/qplot_trajectory.R
- R/utils.R
- tests/testthat/_snaps/plot_techmix.md
- tests/testthat/test-plot_techmix.R
Replace `env  = parent.frame()` with `env = list(data = substitute(data))`
This is more flexible: It allows to move the make the final
substitution at any depth in the call stack.
This solves the same main concern than #385 with less changes.
My focus here was to make the diffs as small as possible.
--
Reference: http://adv-r.had.co.nz/Computing-on-the-language.html#substitute
> Use a list as an environment for substitute()

- _pkgdown.yml
The r2dii meta package is poorly maintained so it's likely best
to not point external users to it.
> Remove link to r2dii

- .github/workflows/R-CMD-check.yaml
The GH actions we use mostly come from r-lib/actions. This PR updates
the R CMD check workflow to catch up with latest changes in r-lib/actions.
This is not crucial for the workings of this package but I think it's nice to
not let this repo fall behind the improvements in r-lib/actions and the
changes in other r2dii packages.
> Catch up with R CMD check workflow in r-lib/actions

- _pkgdown.yml
The section "Get started" is gone. I must have removed it by
accident. This commit restores it.
> Restore Get started

- vignettes/r2dii-plot.Rmd
The motivation to avoid a confusing warning when the data is piped
into qplot_techmix() rather than passed as the first argument. In
that case the warning prints:
Do you want to plot different years? E.g. filter . with:`subset(., year %in% c(2020, 2030))`.
Note the "." where you expect "data".
Along the way, I noted inconsistent use of pipeing versus passing
data, so here I ensure all calls pass data.
I also like this because it makes a clearer distinction between
manipulation of data and plots.
> Separate data from plot

- .github/workflows/check-full.yaml
- .github/workflows/check-full_r2dii-devel.yaml
In this PR I add a GitHub action to check if the package works with devel versions of other `r2dii` packages.
I based it on GH action from `r2dii.analysis` package: https://github.com/2DegreesInvesting/r2dii.analysis/blob/main/.github/workflows/check-full_r2dii-devel.yaml
> Add action checking compatibility with development versions of r2dii

- tests/testthat/_snaps/plot_emission_intensity.md
- tests/testthat/_snaps/plot_techmix.md
- tests/testthat/_snaps/plot_trajectory.md
- tests/testthat/_snaps/sda.md
I reviewed all of these locally, and they come from: 
* API changes in how `dplyr` output is displayed
* API changes in how `errors` and `warnings` are displayed
None of them represent actual differences in values or content.
> accept new `testthat` snapshot results

- data-raw/update_market_share_csv.R
- data-raw/update_sda_csv.R
- tests/testthat/test-market_share.R
- tests/testthat/test-sda.R
- vignettes/r2dii-plot.Rmd
I have replace all references to `ald` and `ald_demo` with the new values `abcd` and `abcd_demo`. This avoids deprecation warnings from other packages. 
Relates to: 
https://github.com/RMI-PACTA/r2dii.data/pull/280
https://github.com/RMI-PACTA/r2dii.match/pull/400
https://github.com/RMI-PACTA/r2dii.analysis/pull/407
> Replace all `ald` references with `abcd`

- R/plot_emission_intensity.R
- R/plot_techmix.R
- R/plot_trajectory.R
- R/utils.R
- tests/testthat/_snaps/sda.md
- tests/testthat/test-plot_emission_intensity.R
- tests/testthat/test-plot_techmix.R
- tests/testthat/test-plot_trajectory.R
- tests/testthat/test-qplot_emission_intensity.R
- vignettes/r2dii-plot.Rmd
Closes #500 
Closes #507 
Update code so checks are passing.
> Fix checks

- tests/testthat/_snaps/plot_techmix.md
- tests/testthat/test-market_share.R
Presumably, these lines restricted the number of lines of demo data being used to improve performance (?), but this makes the test very sensitive to legitimate changes in the demo datasets, e.g. if the explicitly specified rows no longer contain matching rows. An incoming update to the demo datasets in https://github.com/RMI-PACTA/r2dii.data/pull/316 will make this test fail, but this PR will allow it to pass by removing the explicit filtering of rows. https://github.com/RMI-PACTA/r2dii.plot/blob/b4b87e8a3fe0a07367b1de15ef097250507f258e/tests/testthat/test-market_share.R#L43-L44
EDIT: also had to update a snapshot to take into account a newly added (by rlang developers, unrelated to this PR) `<rlang_message>` tag so that tests here pass
EDIT: tests still fail because apparently existing …
> use full demo data in test to avoid problem using new demo data

- NEWS.md
- R/plot_techmix.R
Closes #513 
In this PR I add a filter to techmix prep function so that it filters out the scenario bar for start year. I did not keep the option to display the scenario bar in the current year as it does not make much sense to look at scenario in the start year as it is always equal to the portfolio.
> Remove current scenario bar from techmix

- .github/workflows/add-prs-and-issues-to-project.yml
I use two personal GH projects as an easy dashboard to view all open issues and PRs. 
I have two projects, one for the r2dii suite, and one for all of the repositories I maintain. 
This PR adds a workflow to add issues and PRs to each of them automatically. 
At this stage, I prefer not to share the project since I think it may be a sub-optimal solution.
I think in the future, we may want to do something more like this:
https://github.com/RMI-PACTA/Actions/issues/17
So this PR is just a band-aid for me until the above is closed (hopefully next sprint). 
Let me know if you have any questions :-) 
See also https://github.com/RMI-PACTA/r2dii.match/pull/441
> Add issues and PRs to GH projects

- R/plot_emission_intensity.R
- R/prep_emission_intensity.R
- tests/testthat/_snaps/plot_emission_intensity.md
- tests/testthat/_snaps/prep_emission_intensity.md
- tests/testthat/test-plot_emission_intensity.R
- tests/testthat/test-prep_emission_intensity.R
- tests/testthat/test-scale_colour_r2dii.R
The crucial difference between the input to `prep_emission_intensity` and the input to `plot_emission_intensity` (that I can see) is that the latter has the additional `label` column.
There is an "optional" difference, dependent on the value of `span_5yr`, but I don't think it makes sense to check for that since `plot_*` can't know a-priori what the argument passed to `prep_*` was.
The rest of the checks (that the input data is a data-frame etc.) are shared between the two functions.
Note: I wonder, perhaps we should add an exclusion test that the column `label` is NOT in the input to `prep_emission_intenstiy()`. @MonikaFu let me know if you have thoughts there.
Note: Adding the check brought a few bugs in the unit tests to light! woo 👯
Maybe closes #546 
Relates to #548
> Add more specific input checks for `plot_emission_intensity` and `prep_emission_intensity`

- DESCRIPTION
I believe I removed the only function that uses that dependency here: https://github.com/RMI-PACTA/r2dii.plot/pull/528
But I failed to remove the dependency itself from the `DESCRIPTION` file.
Closes #547
> remove `forcats` dep

- _pkgdown.yml
Similar to what was done in https://github.com/RMI-PACTA/r2dii.match/pull/499, this modernizes the pkgdown config and fixes some problems, e.g. the text being black instead of white in the current dev version of the site at https://rmi-pacta.github.io/r2dii.plot/dev/
note: authors section is removed from pkgdown config because authors are automatically inferred from DESCRIPTION
> modernize pkgdown site in line with other r2dii packages

- DESCRIPTION
- R/scale_colour_r2dii.R
- R/scale_colour_r2dii_sector.R
- R/scale_colour_r2dii_tech.R
- resolves #577 
`scale_name` is [deprecated as of {ggplot2} v3.5.0](https://ggplot2.tidyverse.org/news/index.html#breaking-changes-3-5-0)
used the same strategy as [here](https://github.com/nanxstats/ggsci/pull/26) and [here](https://github.com/nanxstats/ggsci/pull/30) to adapt but remain backward compatible with {ggplot2} < v3.5.0
⚠️ note: @MonikaFu I didn't see the original deprecation warning mentioned in #577, but I now see messages in the tests about a colour scale being replaced 🤷🏻 
> Scale for colour is already present.
> Adding another scale for colour, which will replace the existing scale.
> don't use `scale_name` with {ggplot2} v3.5.0+

- DESCRIPTION
- R/prep_trajectory.R
- man/prep_trajectory.Rd
- resolves #594
- also fixes this section in the documentation https://rmi-pacta.github.io/r2dii.plot/reference/prep_trajectory.html#arg-convert-label
using
https://github.com/RMI-PACTA/r2dii.plot/blob/31331f32690c7765b140c0554eb8446945c8f26c/R/prep_trajectory.R#L8
requires setting `fun` and `value` because of the parameters used here
https://github.com/RMI-PACTA/r2dii.plot/blob/31331f32690c7765b140c0554eb8446945c8f26c/man-roxygen/convert_label.R#L1-L5
⚠️ note that using `@template` and `@templateVars` appears to be [superseded and no longer recommended](https://roxygen2.r-lib.org/articles/reuse.html#superseded)
> set values for doc template in `prep_trajectory()`
