RMI-PACTA/r2dii.plot

.Rbuildignore
.gitignore

This PR creates a pkdown website to be published at https://2degreesinvesting.github.io/r2dii.ggplot/

Add a pkgdown website via use_pkgdown()

---

DESCRIPTION

DESCRIPTION is a picky file. It is a very special file because it
defines an R package. CRAN is very picky about how to write it;
for example, the title must use Title Case not Sentense case and
not end in dot ".". Also, they try to avoid the use of the word
'package' and they ask for package names.
This convensions are totally idiosyncratic and not worth learning
unless you submit to CRAN. But as I'm here, why not try meet those
CRAN policies?

Polish DESCRIPTION

---

R/prepare_for_trajectory_chart.R
tests/testthat/test-prepare_for_trajectory_chart.R

Closes #20 
In this PR I add a filter that ensures that the trajectory chart data start year is the start year of 'projected'.

Fix bug trajectory

---

R/plot_timeline.R
man/plot_timeline.Rd

Add minimal example to plot_timeline()

---

R/plot_trajectory.R
man/plot_trajectory.Rd

Add minimal example to plot_trajectory

---

R/prepare_for_trajectory_chart.R
man/prepare_for_trajectory_chart.Rd

Fix example to show returned value

---

R/prepare_for_techmix_chart.R

Add minimal example to prepare_for_techmix_chart

---

R/theme_2dii_ggplot.R
man/theme_2dii_ggplot.Rd

Add minimal example to theme_2dii_ggplot()

---

R/plot_trajectory.R
man/plot_trajectory.Rd

Closes #112 
In this PR I simplify the way that `additional_line_metrics` is defined and used in code.

Simplify additional line metrics

---

R/prepare_input_data.R

This PR refactors `prapare_input_data()` to capture my new understanding of what this function does:
1. add a new column `metric_type`
2. remove the prefix 'target_' from the existing column `metric`.

Refactor prepare_input_data()

---

DESCRIPTION
R/plot_techmix.R
R/plot_timeline.R
R/plot_trajectory.R
R/timeline_specs.R
man/plot_timeline.Rd
tests/testthat/helper.R
tests/testthat/test-plot_techmix.R
tests/testthat/test-plot_timeline.R

Closes #143 
In this PR I refactor trajectory chart plot, moving parts of the code into separate functions with clear names.

Refactor trajectory

---

R/plot_timeline.R
man/plot_timelineA.Rd

This PR extends the examples of `plot_timeline()`﻿
to show how users may use ggplot2 to change the
colour of the plot lines and legends.

Show how to change colours

---

R/colours.R
_pkgdown.yml
man/colours.Rd

This PR improves the organization of the reference section of the package's website. It touches no production code.

Structure website's reference section

---

R/plot_timeline.R
man/plot_timelineA.Rd

Remove a needless chunk of code from an example. It touches no production code so quite safe to merge without review.

remove needless example chunk

---

R/maybe-dead-code.R
R/plot_trajectoryX.R
man/plot_trajectoryX.Rd
vignettes/articles/r2dii-plot-X.Rmd
vignettes/articles/r2dii-plot-Y.Rmd

I edit the `plot_trajectoryX()` so that it uses the 'main_line' argument and Polish some of the examples in X and Y articles.

Edit articles

---

vignettes/articles/r2dii-plot-X.Rmd
vignettes/articles/r2dii-plot-Y.Rmd

In this PR we plotting examples and customisations more so that it is clearly visible what are the differences between the two interfaces.

Align X and Y articles

---

vignettes/articles/r2dii-plot-Y.Rmd

I prefer `tibble()` over `data.frame()`, but more prefer `data.frame()` over mixing both -- so this PR sticks to only `data.frame()`.

Use only data.frame()

---

DESCRIPTION
man/r2dii.plot-package.Rd

Polish DESCRIPTION Title and Description

---

.github/workflows/R-CMD-check.yaml
.github/workflows/test-coverage.yaml

Forgot to make this work on PRs.

Trigger CI on PR too

---

DESCRIPTION
man/r2dii.plot-package.Rd

Closes #277
This incorporates latest changes to the collaborative google doc
where we collected feedback about this package's title and
description.

Update DESCRIPTION's Title and Description

---

R/plot_trajectory.R
R/utils.R

Relates to #261
﻿- Remove dead code
- Refactor

Remove dead code and increase test coverage

---

R/plot_trajectory.R
R/utils.R
tests/testthat/_snaps/plot_trajectory.md
tests/testthat/test-plot_trajectory.R

- Quiet needless messages
- Quiet needless messages

Handle messages so they don't pollute test output

---

README.md

DRY run of CRAN submission

---

DESCRIPTION

Closes #313 
Initial CRAN submission. Now waiting for CRAN.

r2dii.plot 0.0.1

---

DESCRIPTION
NEWS.md

Relates to #313
﻿- Add NEWS.md
- Increment version number

Follow up initial release

---

NEWS.md

This PR follows up #328. From now on we need to keep track
of user-facing changes in NEWS.md, and polish it just
before the next release. Changes that do not face users
(e.g. refactoring) do not need to be reported﻿ (although
sometimes I patch a version with only internal changes and
report "* Maintenance release" in NEWS.

Report latest user-facing NEWS

---

R/utils.R

Follow up refactoring R/utils.R, mostly removing 
dead code.﻿

Refactor R/utils.R

---

README.Rmd
README.md

Closes #331
Show how to install form CRAN
Use CRAN badge
This follows the release of r2dii.plot 0.0.1 (#313). It touches no production code and is standard so I'll merge without further review.

331 Update installation instructions following cran realease

---

R/plot_trajectory.R
R/qplot_trajectory.R
tests/testthat/_snaps/qplot_trajectory.md

This PR is totally optional. It includes small refactorings.

Small refactorings

---

R/plot_techmix.R
R/plot_trajectory.R
R/utils.R
tests/testthat/test-plot_techmix.R
vignettes/articles/r2dii-plot.Rmd

In this PR I fix techmix code so that it uses custom 'label_tech' if present in the data.
(I also moved commonly used functions to `utils.R`.

Fix label tech

---

R/plot_techmix.R
tests/testthat/test-plot_techmix.R

Closes #365 
In this PR I extend the functionality of `techmix_labels()` function to order the labels.

Order techmix bars

---

DESCRIPTION

New release

---

DESCRIPTION

Use George's suggestion on July 8 at
https://docs.google.com/document/d/1x7Ac0gZrqVffq5eTUXtepPdYa_Yskw4H2AO2rcnUDGU/edit?usp=sharing﻿

Use suggestion by George

---

_pkgdown.yml

I see pkgdown.yml is a lil different than that of other r2dii
packages. This PR makes it consistent with other r2dii packages.

Reuse _pkgdown.yml from r2dii.analysis

---

_pkgdown.yml

This PR adds a link to the blog post category where we advertise exciting news.

add link to blog

---

DESCRIPTION
NEWS.md

This should have been the first commit after
releasing r2dii.plot 0.1.0﻿.
It seems I forgot to do this step -- as it appears
unchecked at https://github.com/2DegreesInvesting/r2dii.plot/issues/369

Use dev version

---

tests/testthat/test-scale_r2dii_tech.R

Extends #399 
This PR wraps fits a couple of lines in 80 characters.

Wrap lines at 80 chars: tests

---

R/utils-tests.R
tests/testthat/test-plot_emission_intensity.R
tests/testthat/test-plot_techmix.R
tests/testthat/test-plot_trajectory.R
tests/testthat/test-qplot_emission_intensity.R
tests/testthat/test-qplot_techmix.R
tests/testthat/test-qplot_trajectory.R
tests/testthat/test-scale_colour_r2dii.R
tests/testthat/test-scale_colour_r2dii_sector.R
tests/testthat/test-scale_colour_r2dii_tech.R

(Extend #417) DRY tests

---

vignettes/r2dii-plot.Rmd

- Remove needless call to glue()
- Replace subset() with filter()

polish article

---

vignettes/r2dii-plot.Rmd

In this PR I improve article text so that it is more clear and easier to follow.
Happy to see feedback on the text itself @maurolepore !

Improve r2dii.plot article

---

R/plot_trajectory.R
tests/testthat/test-plot_trajectory.R

Closes https://github.com/2DegreesInvesting/r2dii.plot/issues/464
In this PR I change the way that trajectory chart area borders are calculated so that the 0 values in the data result in a correct plot.

fix bug trajectory clean

---

R/to_title.R
tests/testthat/test-to_title.R

Closes #439 
This PR makes label conversion more robust in terms of letter cases.

Make label helpers more robust

---

DESCRIPTION
NEWS.md

Increment version number to 0.3.1

---

R/utils.R
tests/testthat/test-plot_emission_intensity.R

Ensure `plot_emission_intensity` with input data having `label` column, outputs custom colour scale with expected order

---

R/plot_emission_intensity.R
tests/testthat/test-plot_emission_intensity.R

`plot_emission_intensity(..., convert_label = to_title)` plays nicely with `scale_colour_r2dii`

---

DESCRIPTION
NEWS.md

release: Increment version number to 0.4.0

---

DESCRIPTION
NEWS.md

release: bump dev version 0.4.0.9000

---

DESCRIPTION
_pkgdown.yml

Relates to https://github.com/RMI-PACTA/pacta.multi.loanbook.plot/pull/32

docs: use rmi pkgdown template

---

DESCRIPTION
NEWS.md

relates to #589 
* increments version number to 0.5.0

release 0.5.0

---

DESCRIPTION
NEWS.md

closes #599 
- increments version number to 0.5.1.9000

Increment version number to 0.5.1.9000

---

DESCRIPTION
R/data_dictionary.R
R/plot_trajectory.R
R/utils.R
tests/testthat/test-plot_emission_intensity.R
tests/testthat/test-prep_techmix.R
tests/testthat/test-scale_colour_r2dii.R

style code with `styler::style_pkg()`

---

.Rbuildignore
DESCRIPTION
R/prep_emission_intensity.R
R/prep_techmix.R
R/prep_trajectory.R
R/utils-docs.R
man-roxygen/convert_label.R
man/prep_emission_intensity.Rd
man/prep_techmix.Rd
man/prep_trajectory.Rd

- resolves #598
as recommended here https://roxygen2.r-lib.org/articles/reuse.html#superseded

replace Roxygen template with inline function
